<?php
namespace App\Controllers;

use App\Models\BookModel;
use App\Repositories\BookRepository;
use RuntimeException;
use Throwable;

class BookController{
    private BookRepository $repo;
    
    public function __construct()
    {
        $this->repo = new BookRepository();
    }
    
    /*
        Insert book function
    */
    public function save():void{
        try {
            $data = json_decode(file_get_contents('php://input'),true);
            
            if (!$data) {
                http_response_code(400);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Invalid book data'
                ]);
                return;
            }
            
            // Validate required fields
            $requiredFields = ['title', 'price', 'stock', 'author_id', 'category_id', 'published_date'];
            foreach ($requiredFields as $field) {
                if (!isset($data[$field]) || $data[$field] === '' || $data[$field] === null) {
                    http_response_code(400);
                    echo json_encode([
                        'status' => 'error',
                        'message' => "Missing required field: $field"
                    ]);
                    return;
                }
            }
            
            // Validate numeric fields
            if (!is_numeric($data['price']) || !is_numeric($data['stock']) || !is_numeric($data['author_id']) || !is_numeric($data['category_id'])) {
                http_response_code(400);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Price, stock, author_id, and category_id must be numeric'
                ]);
                return;
            }
            
            $book = new BookModel(
                0,  // id - will be auto-generated by database
                $data['title'],
                $data['description'] ?? '',
                $data['price'],
                $data['stock'],
                $data['author_id'],
                $data['category_id'],
                $data['book_img'] ?? '',  
                $data['published_date']
            );
        
            if($this->repo->saveBook($book)){
                http_response_code(201);
                echo json_encode([
                    'status'=>'success',
                    'message'=>'Book created successfully',
                ]);
            }else{
                http_response_code(500);
                echo json_encode([
                    'status'=> 'error',
                    'message'=>'Failed to create book'
                ]);
            }
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        } catch (Throwable $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => 'Server error: ' . $err->getMessage()
            ]);
        }
    }
    /*
        get all book function
    */
    public function index():void{
        try {
            $categoryId = null;
            if (isset($_GET['category_id']) && is_numeric($_GET['category_id'])) {
                $categoryId = (int) $_GET['category_id'];
            }

            $books = $this->repo->index($categoryId);
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $books
            ]);
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }    
    
     /*
        get book by id function
    */
   public function get(int $id): void
    {
        try {
            $book = $this->repo->getID($id);
            
            if (!$book) {
                http_response_code(404);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Book not found'
                ]);
                return;
            }
            
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $book
            ]);
            
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }
    /*
        Delete book by id
    */
    public function delete(int $id): void
    {
        try {
            $isDeleted = $this->repo->delete($id);

            if ($isDeleted) {
                http_response_code(200);
                echo json_encode([
                    'status' => 'success',
                    'message' => 'Book deleted successfully'
                ]);
            } else {
                http_response_code(404);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Book not found'
                ]);
            }
        } catch (RuntimeException $e) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => 'Error deleting book: ' . $e->getMessage()
            ]);
        }
    }

    /**
     * Update book by id
     */
    public function update(int $id): void
    {
        try {
            $id = (int)$id; // SAFETY CAST

            $data = json_decode(file_get_contents('php://input'), true);
            if (!$data) {
                http_response_code(400);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Invalid book data'
                ]);
                return;
            }

            $book = new BookModel(
                $id,
                $data['title'],
                $data['description'],
                $data['price'],
                $data['stock'],
                $data['author_id'],
                $data['category_id'],
                $data['book_img'],
                $data['published_date']
            );

            if ($this->repo->update($id, $book)) {
                http_response_code(200);
                echo json_encode([
                    'status' => 'success',
                    'message' => 'Book updated successfully'
                ]);
            } else {
                http_response_code(500);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Failed to update book'
                ]);
            }
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

    /* Get all authors */
    public function indexAuthors(): void
    {
        try {
            $authors = $this->repo->getAuthors();
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $authors
            ]);
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

    /* Get all categories */
    public function indexCategories(): void
    {
        try {
            $categories = $this->repo->getCategories();
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $categories
            ]);
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

    /* Create new category */
    public function saveCategory(): void
    {
        try {
            $data = json_decode(file_get_contents('php://input'), true);
            if (!$data || empty(trim($data['name'] ?? ''))) {
                http_response_code(400);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Invalid category data'
                ]);
                return;
            }

            $isSaved = $this->repo->saveCategory(trim($data['name']));
            if ($isSaved) {
                http_response_code(201);
                echo json_encode([
                    'status' => 'success',
                    'message' => 'Category created successfully'
                ]);
            } else {
                http_response_code(500);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Failed to create category'
                ]);
            }
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

    /* Update category */
    public function updateCategory(int $id): void
    {
        try {
            $data = json_decode(file_get_contents('php://input'), true);
            if (!$data || empty(trim($data['name'] ?? ''))) {
                http_response_code(400);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Invalid category data'
                ]);
                return;
            }

            $isUpdated = $this->repo->updateCategory($id, trim($data['name']));
            if ($isUpdated) {
                http_response_code(200);
                echo json_encode([
                    'status' => 'success',
                    'message' => 'Category updated successfully'
                ]);
            } else {
                http_response_code(404);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Category not found or no changes made'
                ]);
            }
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

    /* Delete category */
    public function deleteCategory(int $id): void
    {
        try {
            $isDeleted = $this->repo->deleteCategory($id);
            if ($isDeleted) {
                http_response_code(200);
                echo json_encode([
                    'status' => 'success',
                    'message' => 'Category deleted successfully'
                ]);
            } else {
                http_response_code(404);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Category not found'
                ]);
            }
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

}