<?php
namespace App\Controllers;

use App\Models\BookModel;
use App\Repositories\BookRepository;
use RuntimeException;

class BookController{
    private BookRepository $repo;
    
    public function __construct()
    {
        $this->repo = new BookRepository();
    }
    
    /*
        Insert book function
    */
    public function save():void{
        $data = json_decode(file_get_contents('php://input'),true);
        
        $book = new BookModel(
            0,  // id - will be auto-generated by database
            $data['title'],
            $data['description'],
            $data['price'],
            $data['stock'],
            $data['author_id'],
            $data['category_id'],
            $data['book_img'],  
            $data['published_date']
        );
    
        if($this->repo->saveBook($book)){
            http_response_code(201);
            echo json_encode([
                'status'=>'success',
                'message'=>'Book created successfully',
            ]);
        }else{
            http_response_code(500);
            echo json_encode([
                'status'=> 'error',
                'message'=>'Failed to create book'
            ]);
        }
    }
    /*
        get all book function
    */
    public function index():void{
        try {
            $books = $this->repo->index();
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $books
            ]);
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }    
    
     /*
        get book by id function
    */
   public function get(int $id): void
    {
        try {
            $book = $this->repo->getID($id);
            
            if (!$book) {
                http_response_code(404);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Book not found'
                ]);
                return;
            }
            
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $book
            ]);
            
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }
    /*
        Delete book by id
    */
    public function delete(int $id): void
    {
        try {
            $isDeleted = $this->repo->delete($id);

            if ($isDeleted) {
                http_response_code(200);
                echo json_encode([
                    'status' => 'success',
                    'message' => 'Book deleted successfully'
                ]);
            } else {
                http_response_code(404);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Book not found'
                ]);
            }
        } catch (RuntimeException $e) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => 'Error deleting book: ' . $e->getMessage()
            ]);
        }
    }

    /**
     * Update book by id
     */
    public function update(int $id): void
    {
        try {
            $id = (int)$id; // SAFETY CAST

            $data = json_decode(file_get_contents('php://input'), true);
            if (!$data) {
                http_response_code(400);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Invalid book data'
                ]);
                return;
            }

            $book = new BookModel(
                $id,
                $data['title'],
                $data['description'],
                $data['price'],
                $data['stock'],
                $data['author_id'],
                $data['category_id'],
                $data['book_img'],
                $data['published_date']
            );

            if ($this->repo->update($id, $book)) {
                http_response_code(200);
                echo json_encode([
                    'status' => 'success',
                    'message' => 'Book updated successfully'
                ]);
            } else {
                http_response_code(500);
                echo json_encode([
                    'status' => 'error',
                    'message' => 'Failed to update book'
                ]);
            }
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

    /* Get all authors */
    public function indexAuthors(): void
    {
        try {
            $authors = $this->repo->getAuthors();
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $authors
            ]);
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

    /* Get all categories */
    public function indexCategories(): void
    {
        try {
            $categories = $this->repo->getCategories();
            http_response_code(200);
            echo json_encode([
                'status' => 'success',
                'data' => $categories
            ]);
        } catch (RuntimeException $err) {
            http_response_code(500);
            echo json_encode([
                'status' => 'error',
                'message' => $err->getMessage()
            ]);
        }
    }

}